CREATE DATABASE IF NOT EXISTS burgers_db;

USE burgers_db;

CREATE TABLE IF NOT EXISTS burgers(
id INTEGER(10) NOT NULL AUTO_INCREMENT
,burger_name VARCHAR(100) NOT NULL
,devoured BOOLEAN NOT NULL
,time_stamp datetime NOT NULL DEFAULT NOW()
,PRIMARY KEY (id)
);